"""Platform event emitter and domain events."""

from __future__ import annotations

from .bus import (
    DomainEventBus,
    SubscriberFn,
    default_bus,
    publish,
    subscribe,
    unsubscribe,
)
from .domain_events import (
    AssessmentCompleted,
    AssessmentCompletedPayload,
    AssessmentCreated,
    AssessmentCreatedPayload,
    ConfigChanged,
    ConfigChangedPayload,
    DomainEvent,
    LlmCallCompleted,
    LlmCallCompletedPayload,
    ModuleEntityBatchUpserted,
    ModuleEntityBatchUpsertedPayload,
    ModuleWorkflowCompleted,
    ModuleWorkflowCompletedPayload,
    ModuleWorkflowStarted,
    ModuleWorkflowStartedPayload,
    SystemDeregistered,
    SystemDeregisteredPayload,
    SystemRegistered,
    SystemRegisteredPayload,
)
from .emitter import EventEmitter, ThreadSafeEventEmitter, build_emitter
from .event import PlatformEvent
from .redis_bridge import (
    PROCESS_ORIGIN_ID,
    REDIS_STREAM_KEY,
    install_redis_publisher,
    is_inbound_replay,
    start_consumer,
    stop_consumer,
)

__all__ = [
    "AssessmentCompleted",
    "AssessmentCompletedPayload",
    "AssessmentCreated",
    "AssessmentCreatedPayload",
    "ConfigChanged",
    "ConfigChangedPayload",
    "DomainEvent",
    "DomainEventBus",
    "EventEmitter",
    "LlmCallCompleted",
    "LlmCallCompletedPayload",
    "ModuleEntityBatchUpserted",
    "ModuleEntityBatchUpsertedPayload",
    "ModuleWorkflowCompleted",
    "ModuleWorkflowCompletedPayload",
    "ModuleWorkflowStarted",
    "ModuleWorkflowStartedPayload",
    "PROCESS_ORIGIN_ID",
    "PlatformEvent",
    "REDIS_STREAM_KEY",
    "SubscriberFn",
    "SystemDeregistered",
    "SystemDeregisteredPayload",
    "SystemRegistered",
    "SystemRegisteredPayload",
    "ThreadSafeEventEmitter",
    "build_emitter",
    "default_bus",
    "install_redis_publisher",
    "is_inbound_replay",
    "publish",
    "start_consumer",
    "stop_consumer",
    "subscribe",
    "unsubscribe",
]
