"""Public contract models for the vulnerability research module.

Barrel re-export only. Model definitions live in domain submodules.
"""
from __future__ import annotations

from .advisory import CVSSVector, CWEMapping, VRAdvisory
from .audit_memo import (
    AuditMemoCreate,
    AuditMemoScope,
    AuditMemoSummary,
)
from .branch import (
    BranchOperation,
    BranchStatus,
    PersonaVoice,
    VRBranchSummary,
)
from .disclosure import (
    ArtifactTier,
    DisclosureKind,
    DisclosureSubmissionStatus,
    DisclosureTrackInfo,
    RenderedSubmission,
    VRDisclosureSubmissionCreate,
    VRDisclosureSubmissionPatch,
    VRDisclosureSubmissionSummary,
)
from .enrichment import (
    EnrichmentError,
    EnrichmentResult,
    MitigationFlags,
    TargetCapabilityProfile,
)
from .finding import (
    CrashSignature,
    CrashType,
    DisclosureStatus,
    PoCResult,
    VRFinding,
)
from .fuzz import (
    CampaignStatus,
    CrashSeverity,
    CrashTriageVerdict,
    FuzzEngineId,
    FuzzStrategyId,
    VRFuzzCampaignCreate,
    VRFuzzCampaignPatch,
    VRFuzzCampaignSummary,
    VRFuzzCrashCreate,
    VRFuzzCrashSummary,
)
from .investigation import (
    InvestigationKind,
    InvestigationPauseReason,
    InvestigationStatus,
    VRInvestigationCreate,
    VRInvestigationSummary,
)
from .investigation_target import (
    InvestigationTargetRole,
    VRInvestigationTargetAttach,
    VRInvestigationTargetDetach,
    VRInvestigationTargetSummary,
)
from .message import (
    OperatorIntent,
    PayloadKind,
    SenderKind,
    VRMessageCreate,
    VRMessageSummary,
)
from .outcome import (
    OutcomeConfidence,
    OutcomeDispatchStatus,
    OutcomeKind,
    VROutcomeCreate,
    VROutcomeSummary,
)
from .pattern import (
    PatternConfidence,
    PatternKind,
    PatternScope,
    PatternStatus,
    VRPatternCreate,
    VRPatternPatch,
    VRPatternSummary,
)
from .project import (
    InputSource,
    TargetClass,
    TargetFormat,
    TargetIngestionSpec,
    VRProjectCreate,
    VRProjectStatus,
    VRProjectSummary,
)
from .target import (
    EnrichmentStatus,
    TargetKind,
    TargetStatus,
    TargetTag,
    TargetTagSource,
    VRTargetCreate,
    VRTargetPatch,
    VRTargetSummary,
)
from .workspace import (
    VRWorkspaceCreate,
    VRWorkspacePatch,
    VRWorkspaceSummary,
    WorkspaceStatus,
    WorkspaceTheme,
)

__all__ = [
    "AuditMemoCreate",
    "AuditMemoScope",
    "AuditMemoSummary",
    "BranchOperation",
    "BranchStatus",
    "CVSSVector",
    "CWEMapping",
    "CrashSignature",
    "CrashType",
    "DisclosureStatus",
    "ArtifactTier",
    "DisclosureKind",
    "DisclosureSubmissionStatus",
    "DisclosureTrackInfo",
    "RenderedSubmission",
    "VRDisclosureSubmissionCreate",
    "VRDisclosureSubmissionPatch",
    "VRDisclosureSubmissionSummary",
    "EnrichmentError",
    "EnrichmentResult",
    "EnrichmentStatus",
    "InputSource",
    "InvestigationKind",
    "InvestigationPauseReason",
    "InvestigationStatus",
    "InvestigationTargetRole",
    "VRInvestigationTargetAttach",
    "VRInvestigationTargetDetach",
    "VRInvestigationTargetSummary",
    "MitigationFlags",
    "OperatorIntent",
    "OutcomeConfidence",
    "OutcomeDispatchStatus",
    "OutcomeKind",
    "PatternConfidence",
    "PatternKind",
    "PatternScope",
    "PatternStatus",
    "PayloadKind",
    "PersonaVoice",
    "PoCResult",
    "SenderKind",
    "TargetCapabilityProfile",
    "TargetClass",
    "TargetFormat",
    "TargetIngestionSpec",
    "TargetKind",
    "TargetStatus",
    "TargetTag",
    "TargetTagSource",
    "VRAdvisory",
    "VRBranchSummary",
    "VRFinding",
    "VRFuzzCampaignCreate",
    "VRFuzzCampaignPatch",
    "VRFuzzCampaignSummary",
    "VRFuzzCrashCreate",
    "VRFuzzCrashSummary",
    "CampaignStatus",
    "CrashSeverity",
    "CrashTriageVerdict",
    "FuzzEngineId",
    "FuzzStrategyId",
    "VRInvestigationCreate",
    "VRInvestigationSummary",
    "VRMessageCreate",
    "VRMessageSummary",
    "VROutcomeCreate",
    "VROutcomeSummary",
    "VRProjectCreate",
    "VRProjectStatus",
    "VRProjectSummary",
    "VRPatternCreate",
    "VRPatternPatch",
    "VRPatternSummary",
    "VRTargetCreate",
    "VRTargetPatch",
    "VRTargetSummary",
    "VRWorkspaceCreate",
    "VRWorkspacePatch",
    "VRWorkspaceSummary",
    "WorkspaceStatus",
    "WorkspaceTheme",
]
