export const nav = [
  {
    id: "vr.projects",
    slot: "sidebar.main" as const,
    label: "Vuln Research",
    to: "/vr",
    order: 70,
    description: "N-day vulnerability research projects",
  },
  {
    id: "vr.investigations",
    slot: "sidebar.main" as const,
    label: "Investigations",
    to: "/vr/investigations",
    order: 71,
    description: "Hypothesis-driven investigations across targets",
  },
  {
    id: "vr.workspaces",
    slot: "sidebar.main" as const,
    label: "Workspaces",
    to: "/vr/workspaces",
    order: 69,
    description: "Thematic workspaces grouping related VR targets",
  },
  {
    id: "vr.targets",
    slot: "sidebar.main" as const,
    label: "Targets",
    to: "/vr/targets",
    order: 69.5,
    description: "Persistent VR targets across workspaces",
  },
  {
    id: "vr.patterns",
    slot: "sidebar.main" as const,
    label: "Patterns",
    to: "/vr/patterns",
    order: 72,
    description: "Reusable patterns extracted from successful investigations",
  },
  {
    id: "vr.disclosures",
    slot: "sidebar.main" as const,
    label: "Disclosures",
    to: "/vr/disclosures",
    order: 73,
    description: "Multi-track disclosure submission lifecycle",
  },
  {
    id: "vr.fuzz-campaigns",
    slot: "sidebar.main" as const,
    label: "Fuzz Campaigns",
    to: "/vr/fuzz/campaigns",
    order: 74,
    description: "Fuzzing campaigns + crash triage",
  },
  {
    id: "vr.mcp-servers",
    slot: "sidebar.main" as const,
    label: "MCP Servers",
    to: "/vr/mcp/servers",
    order: 75,
    description: "Configure + monitor delegated MCP workstations",
  },
  {
    id: "vr.mcp-calls",
    slot: "sidebar.main" as const,
    label: "MCP Call Log",
    to: "/vr/mcp/calls",
    order: 76,
    description: "Live audit trail of every MCP call AILA forwarded",
  },
];
