"""SbdNfrConfig contract — module configuration model for the SbD NFR module.

This model crosses the service boundary and therefore lives in contracts/ so
callers (ConfigRegistry, router, tests) can import it without pulling in the
full services layer.

Design references: D-14 (branding config), D-58 (module config namespace),
T-134-13 (config bounds), T-136-01 (org_logo_url URL validation),
T-136-02 (primary_color hex validation).

Security note (T-134-13): All numeric settings use Pydantic Field(ge=..., le=...)
bounds so ConfigRegistry.set() type-validation rejects out-of-range values before
they reach the database.

Security note (T-136-02): primary_color is validated as a CSS hex color (#RRGGBB)
to prevent CSS injection in report templates.

Security note (T-136-01): org_logo_url must be empty or a valid http/https URL;
it is never fetched server-side — browser-only in HTML preview, data URI required
for PDF mode (enforced in Plan 02 pdf_service).
"""

from __future__ import annotations

import re

from pydantic import BaseModel, Field, field_validator

__all__ = ["SbdNfrConfig"]

_HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")
_URL_RE = re.compile(r"^(https?://\S+)?$")


class SbdNfrConfig(BaseModel):
    """Module configuration for the SbD NFR assessment module (D-14, D-58).

    Registered under the 'sbd_nfr' namespace via ConfigRegistry.register().
    Default values are written to ConfigEntryRecord on first registration;
    existing DB rows are not overwritten (user overrides survive restarts).

    Operational fields:
        max_sessions_per_user: Maximum active non-deleted sessions a single user
            may own simultaneously.
        auto_archive_days: Number of days after which idle sessions are eligible
            for automatic archival (future maintenance job).
        draft_expiry_days: Number of days a draft session may remain without
            any activity before it is considered expired.
        require_all_sections: When True, all questionnaire sections must be
            completed before a session can be submitted.
        smart_search_enabled: Enables vector-search-assisted question lookup
            in the wizard frontend.
        share_link_enabled: Allows requesters to generate a public share link
            for their session (read-only access via share_token).

    Branding fields (D-14):
        questionnaire_title: Display title shown at the top of the wizard.
        report_subtitle: Sub-title shown on generated report output.
        org_name: Organisation name used in report headers and footers.
        org_logo_url: Optional URL to organisation logo (empty string = no logo).
            Must be empty or a valid http/https URL (T-136-01).
            Never fetched server-side; browser-only in HTML preview.
        primary_color: Hex color (#RRGGBB) for branded report elements (T-136-02).
            Validated as hex to prevent CSS injection.
        footer_text: Text displayed in the report footer.
    """

    # --- Operational fields ---
    max_sessions_per_user: int = Field(default=50, ge=1, le=1000)
    auto_archive_days: int = Field(default=90, ge=1, le=365)
    draft_expiry_days: int = Field(default=30, ge=1, le=365)
    require_all_sections: bool = Field(default=False)
    smart_search_enabled: bool = Field(default=True)
    share_link_enabled: bool = Field(default=True)

    # --- Branding configuration (D-14) ---
    questionnaire_title: str = Field(default="AILA NFR Assessment")
    report_subtitle: str = Field(default="Pre-Meeting Security Assessment Report")
    org_name: str = Field(default="AILA")
    org_logo_url: str = Field(default="")
    primary_color: str = Field(default="#1a56db")
    footer_text: str = Field(default="Generated by AILA Platform")

    @field_validator("primary_color")
    @classmethod
    def validate_hex_color(cls, v: str) -> str:
        """Enforce #RRGGBB format to prevent CSS injection (T-136-02)."""
        if not _HEX_COLOR_RE.match(v):
            raise ValueError(
                f"primary_color must be a CSS hex color in #RRGGBB format, got: {v!r}"
            )
        return v

    @field_validator("org_logo_url")
    @classmethod
    def validate_logo_url(cls, v: str) -> str:
        """Accept empty string or a valid http/https URL (T-136-01)."""
        if v and not _URL_RE.match(v):
            raise ValueError(
                f"org_logo_url must be empty or a valid http/https URL, got: {v!r}"
            )
        return v
