"""Disk-image collector -- detects the image OS and runs Dissect queries."""
from __future__ import annotations

import logging
import re
from typing import Any

# --- Forensic enrichment helpers ------------------------------------------

# Living-Off-The-Land Binaries / Scripts -- legitimate signed Windows tools
# widely abused by attackers for defense evasion. Their presence alone is
# NOT suspicious (every Windows host runs these daily); we only flag them
# when context strengthens the signal -- persistence placement, suspicious
# argument patterns, or unusual parent process.
_LOLBAS: frozenset[str] = frozenset(x.lower() for x in [
    "certutil.exe", "regsvr32.exe", "bitsadmin.exe", "mshta.exe",
    "rundll32.exe", "wmic.exe", "cscript.exe", "wscript.exe",
    "installutil.exe", "powershell.exe", "powershell_ise.exe",
    "msbuild.exe", "msiexec.exe", "forfiles.exe", "scriptrunner.exe",
    "cmd.exe", "schtasks.exe", "psexec.exe", "psexesvc.exe", "ssh.exe",
])

# Paths that legitimate installers almost never write to -- binaries landing
# here nearly always indicate attacker staging or user-land persistence.
_SUSPICIOUS_PATH_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in [
        r"\\AppData\\Local\\Temp\\",
        r"\\AppData\\Roaming\\",
        r"\\Users\\Public\\",
        r"\\ProgramData\\(?!Microsoft\\|Package Cache\\|chocolatey\\)",
        r"\\Windows\\Temp\\",
        r"\\Recycle\.Bin\\",
        r"C:\\Temp\\", r"C:\\Tmp\\", r"C:\\Intel\\Logs\\",
    ]
)

# Location classes that are legitimate-by-design. These are the three
# STRUCTURAL signals a binary path can give us about operator intent -- all
# generalise across any Windows image without knowing a single binary name:
#
#   1. ``\\tsclient\`` -- an RDP client-side drive redirect. By definition
#      an interactive human is running a tool from their own workstation.
#      Attackers with pre-placed implants don't reach back through tsclient.
#
#   2. ``\Program Files\`` / ``\Program Files (x86)\`` / ``\Windows\``
#      (outside the Temp subtrees) -- Windows' canonical install roots.
#      Installers require integrity checks to write here; malware that
#      lands here has either already had admin, or signed MSI delivery --
#      either way, the Temp/AppData staging heuristic would have fired
#      upstream before the binary reached this directory.
#
#   3. Microsoft's own installer staging GUIDs under Temp
#      (``\{GUID\}~setup\``, ``\{GUID\}\.cr\``, ``\{GUID\}\.be\``) -- these
#      are generated by Windows Installer itself for MSI / Bootstrapper
#      extraction. The pattern is universal MS infrastructure, not
#      attacker-controlled; unpacking a legit MSI looks exactly like this
#      on every Windows host since Vista.
_BENIGN_PATH_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in [
        r"\\\\tsclient\\",
        r"\\\{[0-9A-Fa-f\-]{8,}\}~?setup\\",           # {GUID}~setup\ and {GUID}setup\
        r"\\\{[0-9A-Fa-f\-]{8,}\}\\\.(?:cr|be)\\",     # {GUID}\.cr\ and {GUID}\.be\
        r"C:\\Program Files(?: \(x86\))?\\(?!.*\\(Temp|Tmp)\\)",
        r"C:\\Windows\\(System32|SysWOW64|WinSxS|Microsoft\.NET|servicing|assembly)\\",
    ]
)

# Attacker-shaped argument fragments. A LOLBAS invocation with any of
# these in its arguments is genuinely suspicious regardless of placement.
_ATTACKER_ARG_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in [
        r"(?:^|[\s\"'])[-/]enc(?:odedcommand)?\b",    # powershell -enc <base64>
        r"\biex\b", r"\binvoke-expression\b",          # in-memory execution
        r"\bdownloadstring\b", r"\bdownloadfile\b",
        r"\bfrombase64string\b",
        r"\bbypass\b.*\bexecutionpolicy\b|\bexecutionpolicy\b\s+bypass",
        r"\bhidden\b.*\bwindowstyle\b|\bwindowstyle\s+hidden\b",
        r"\bnew-object\s+net\.webclient\b",
        r"\burlcache\b.*\bcertutil\b|\bcertutil\b.*\burlcache\b",
        r"(?:^|[\s\"'])[-/]nop(?:rofile)?\b",          # powershell -nop / -noprofile
        r"(?:^|[\s\"'])[-/]w(?:indowstyle)?\s+hidden",
        r"\bregsvr32\b.*\/i\s*:\s*http",
        r"\bmshta\b\s+http",
        r"\bfrombase64string\b",
    ]
)

# Location classes where a LOLBAS appearance IS suspicious on its own --
# these slots are rare and attacker-shaped. A bare ``rundll32.exe`` entry
# in ``tasks`` is NOT on this list because Windows itself creates hundreds
# of legit rundll32 tasks; tasks only flag when args add signal.
_STRONG_PERSISTENCE_KINDS: frozenset[str] = frozenset({
    "runkeys", "services", "startupinfo",
})


def _first_token(s: str) -> str:
    s = s.strip().strip('"').strip("'")
    if not s:
        return ""
    return s.split()[0]


def _basename(path: str) -> str:
    last = path.replace("/", "\\").rstrip("\\").rsplit("\\", 1)[-1]
    return _first_token(last).lower()


def _mark_suspicious(
    record: dict[str, Any],
    *,
    candidate_fields: tuple[str, ...],
    kind: str = "",
) -> dict[str, Any]:
    """Tag a record with ``suspicious_reasons`` when the record matches one
    of several context-aware heuristics. Designed to minimise false
    positives -- a plain ``powershell.exe`` prefetch entry no longer flags
    as "lolbas"; only when context says so (persistence placement,
    attacker-shaped args, or suspicious path).

    ``kind`` is the collector's artifact type (runkeys / services / tasks /
    startupinfo / prefetch / shellbags / …). Persistence kinds get a stricter
    LOLBAS rule; execution kinds get a looser one.
    """
    reasons: list[str] = []
    blob_parts: list[str] = []
    tokens: list[str] = []

    for f in candidate_fields:
        val = record.get(f)
        if val is None:
            continue
        if isinstance(val, dict):
            ex = str(val.get("executable") or "")
            blob_parts.append(ex)
            args = val.get("args") or []
            blob_parts.append(" ".join(str(a) for a in args))
            if ex:
                tokens.append(_basename(ex))
        else:
            blob_parts.append(str(val))
            tokens.append(_basename(str(val)))

    blob = " ".join(blob_parts).strip()
    if not blob:
        return record
    blob_l = blob.lower()

    # === Positive (attacker-shape) signals scanned FIRST ===
    # The benign path allow-list below only skips the record when no
    # positive signal has fired. A LOLBAS argv with `-enc` cannot be made
    # clean by the fact that its binary lives in System32.
    #
    # Pre-compute whether a benign-path pattern matches the blob. This is
    # used in two places: (a) the suspicious-path check below skips when
    # the same blob also matches a benign pattern (MSI GUID staging
    # directories sit INSIDE Windows\Temp but are legitimate), and (b) the
    # end-of-function short-circuit that drops benign records entirely.
    benign_path_hit = any(pat.search(blob) for pat in _BENIGN_PATH_PATTERNS)

    # Suspicious path -- attacker staging location (AppData\Temp, Windows
    # \Temp without a benign signature, Users\Public, ProgramData root…).
    if not benign_path_hit:
        for pat in _SUSPICIOUS_PATH_PATTERNS:
            if pat.search(blob):
                reasons.append(f"suspicious_path:{pat.pattern}")
                break

    # Attacker-shaped argument fragments are high-signal regardless of kind.
    arg_hit = False
    for pat in _ATTACKER_ARG_PATTERNS:
        if pat.search(blob):
            reasons.append(f"suspicious_arg:{pat.pattern}")
            arg_hit = True
            break

    # Double extension (e.g. invoice.pdf.exe) -- classic phishing dropper.
    if re.search(r"\.(pdf|doc|docx|xls|xlsx|jpg|png|txt)\.(exe|scr|bat|com|ps1|vbs)\b", blob_l):
        reasons.append("double_extension")

    # LOLBAS -- context-aware. A persistence slot (runkeys/services/
    # startupinfo) with any LOLBAS fires. Anywhere else, a LOLBAS only
    # fires when a positive path/arg signal has already been found.
    lolbas_hit: str | None = None
    for tok in tokens:
        if tok in _LOLBAS:
            lolbas_hit = tok
            break
    if lolbas_hit and (
        kind in _STRONG_PERSISTENCE_KINDS
        or arg_hit
        or any(r.startswith("suspicious_path:") for r in reasons)
    ):
        reasons.append(f"lolbas:{lolbas_hit}")

    # === Structural benign-path short-circuit ===
    # Only skip when no attacker-shape signal fired above. Binaries in
    # \\tsclient\, MS-installer GUID dirs, Program Files, or Windows system
    # directories are benign-by-default but NOT unconditionally.
    if not reasons and benign_path_hit:
        return record

    # De-dup while preserving order.
    seen: set[str] = set()
    deduped: list[str] = []
    for r in reasons:
        if r not in seen:
            seen.add(r)
            deduped.append(r)
    if deduped:
        record["suspicious_reasons"] = deduped
    return record

from aila.platform.exceptions import AILAError

from ._helpers import err_sink, safe_emit, sq, truncate

__all__ = ["collect_disk_artifacts"]

_log = logging.getLogger(__name__)

# Queries that genuinely work on every Dissect target. shell.history.bash /
# shell.history.zsh / recentfiles were here but they hard-fail (exit 2) on
# Windows images because bash/zsh don't exist and recentfiles is an xbel
# parser -- moved to the POSIX-specific packs below.
_COMMON_QUERIES: list[tuple[str, str]] = [
    ("hostname", "host"),
    ("users", "user"),
    ("ips", "host"),
    ("timezone", "host"),
    ("browser.history", "browser"),
    ("browser.downloads", "browser"),
    ("browser.extensions", "browser"),
    ("browser.cookies", "browser"),
    ("browser.passwords", "browser"),
    ("usb", "filesystem"),
]
# Query function names MUST match dissect's plugin registry exactly
# (verified via `python -m dissect.target.tools.query --list`). Earlier
# guesses like `shell.history.powershell`, `recent_docs`, `recycle_bin`,
# `startup` are NOT registered -- dissect prints its usage banner and the
# artifact contained raw help text with 0 parsed records.
_WINDOWS_QUERIES: list[tuple[str, str]] = [
    ("domain", "host"),
    ("services", "execution"),
    ("runkeys", "execution"),
    ("prefetch", "execution"),
    ("tasks", "execution"),
    ("startupinfo", "execution"),
    ("shellbags", "execution"),
    ("powershell_history", "execution"),
    ("mru.recentdocs", "filesystem"),
    ("recyclebin", "filesystem"),
]
_LINUX_QUERIES: list[tuple[str, str]] = [
    ("domain", "host"),
    ("services", "execution"),
    ("tasks", "execution"),
    ("bashhistory", "execution"),
    ("commandhistory", "execution"),
    ("recently_used", "filesystem"),
    ("docker.containers", "container"),
    ("docker.images", "container"),
]
_MACOS_QUERIES: list[tuple[str, str]] = [
    ("apps.installed", "execution"),
    ("plist.launchagents", "execution"),
    ("plist.launchdaemons", "execution"),
    ("plist.loginitems", "execution"),
    ("bashhistory", "execution"),
    ("spotlight", "filesystem"),
    ("wifi.known", "network"),
    ("unified_logs", "log"),
]

_HOTSPOT_EXTENSIONS_COMMON = (
    '"*.exe" -o -name "*.dll" -o -name "*.ps1" -o -name "*.bat" '
    '-o -name "*.sh" -o -name "*.py" -o -name "*.elf" -o -name "*.ko" '
    '-o -name "*.so"'
)
_HOTSPOT_EXTENSIONS_MACOS = (
    '"*.app" -o -name "*.dylib" -o -name "*.pkg" -o -name "*.command" '
    '-o -name "*.workflow" -o -name "*.scpt" -o -name "*.kext"'
)


def _queries_for_image(image_os: str) -> list[tuple[str, str]]:
    os_specific = {"windows": _WINDOWS_QUERIES, "linux": _LINUX_QUERIES, "macos": _MACOS_QUERIES}.get(image_os, [])
    return _COMMON_QUERIES + os_specific


async def _detect_disk_os(
    ssh: Any, integration: dict, path: str, analyzer_os: str, emitter: Any = None,
) -> str:
    """Detect the image OS via ``dissect.target.info``. Returns a best-effort string."""
    from aila.modules.forensics.tools._ssh_helper import python_cmd

    py = python_cmd(analyzer_os)
    esink = err_sink(analyzer_os)
    qpath = sq(path, analyzer_os)

    try:
        info = await ssh.run_command(
            integration,
            f"{py} -m dissect.target.tools.info {qpath} {esink}",
            timeout_seconds=120.0,
        )
        lower = info.lower()
        for needles, detected in (
            (("macos", "darwin", "apfs", "hfs", "apple"), "macos"),
            (("windows", "ntfs", "ntoskrnl", "registry"), "windows"),
            (("linux", "ext4", "ext3", "xfs", "btrfs", "debian", "ubuntu", "centos", "fedora"), "linux"),
        ):
            if any(n in lower for n in needles):
                await safe_emit(emitter, "disk_os_detected", f"disk: {path} → {detected}", {"path": path, "image_os": detected})
                return detected
    except (OSError, TimeoutError, RuntimeError, AILAError) as exc:
        _log.debug("disk OS detection via dissect failed for %s: %s", path, exc, exc_info=True)
        await safe_emit(emitter, "disk_os_detect_failed", f"disk: OS detection failed for {path}: {exc}", {"path": path, "error": str(exc)[:200]})

    ext = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    if ext in ("dmg", "sparseimage", "sparsebundle"):
        return "macos"
    return "unknown"


async def collect_disk_artifacts(
    ssh: Any,
    integration: dict,
    path: str,
    analyzer_os: str = "linux",
    emitter: Any = None,
    on_artifact: Any = None,
) -> list[dict[str, Any]]:
    """Run Dissect target-info, OS-appropriate queries, and a hotspot scan on a disk image."""
    from aila.modules.forensics.tools._ssh_helper import python_cmd

    py = python_cmd(analyzer_os)
    esink = err_sink(analyzer_os)
    qpath = sq(path, analyzer_os)
    artifacts: list[dict[str, Any]] = []

    image_os = await _detect_disk_os(ssh, integration, path, analyzer_os, emitter=emitter)
    _log.info("Disk image %s detected as %s", path, image_os)

    # Target info
    try:
        info = await ssh.run_command(
            integration,
            f"{py} -m dissect.target.tools.info {qpath} {esink} || echo dissect unavailable",
            timeout_seconds=120.0,
        )
        art = {
            "family": "host",
            "type": "target_info",
            "source_tool": "dissect",
            "data": {"raw_output": truncate(info, 4000), "evidence_path": path, "image_os": image_os},
        }
        artifacts.append(art)
        if on_artifact:
            await on_artifact(art)
        await safe_emit(emitter, "artifact_added", f"disk: target_info for {path}", {"path": path, "type": "target_info"})
    except (OSError, TimeoutError, RuntimeError, AILAError) as exc:
        _log.debug("dissect target-info failed for %s: %s", path, exc, exc_info=True)
        await safe_emit(emitter, "query_failed", f"disk: target_info failed for {path}: {exc}", {"path": path, "query": "target_info", "error": str(exc)[:200]})

    # Per-query collection
    import json as _json
    import time as _time

    from aila.modules.forensics.tools._ssh_helper import run_command_via_file
    queries = _queries_for_image(image_os)
    await safe_emit(emitter, "disk_queries_begin", f"disk: {len(queries)} dissect queries on {path}", {"path": path, "query_count": len(queries)})
    for qfunc, family in queries:
        # `-j` asks dissect for JSONL output (one record per line). We route
        # the output through a remote temp file + SFTP download instead of
        # piping it back through SSH stdout. Large queries (prefetch, shellbags,
        # recent_docs) produce >2 MB which deadlocks paramiko's channel window;
        # file transfer sidesteps that entirely.
        cmd = f"{py} -m dissect.target.tools.query -j -f {qfunc} {qpath}"
        start_ts = _time.monotonic()
        await safe_emit(
            emitter, "ssh_exec",
            f"disk[{qfunc}]: running (via remote temp file, 300s timeout)",
            {"path": path, "query": qfunc, "command": cmd, "timeout_s": 300},
        )
        try:
            output = await run_command_via_file(ssh, integration, cmd, analyzer_os, timeout_seconds=300.0)
            elapsed = _time.monotonic() - start_ts
            head_sample = "\n".join(output.strip().splitlines()[:5])[:500]
            tail_sample = "\n".join(output.strip().splitlines()[-5:])[:500]
            if output.strip():
                max_records = 1000
                total_records = 0
                parsed_records: list[dict[str, Any]] = []
                parse_errors = 0
                for line in output.strip().splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = _json.loads(line)
                    except _json.JSONDecodeError:
                        parse_errors += 1
                        continue
                    # Dissect's JSONL prefixes each query with a schema line
                    # like {"_type":"recorddescriptor","_data":[...]}. That is
                    # NOT a data row -- it's a column declaration. Skip it so
                    # the frontend table shows real rows instead of one row
                    # of `_type, _data` schema metadata.
                    if isinstance(rec, dict) and rec.get("_type") == "recorddescriptor":
                        continue
                    total_records += 1
                    parsed_records.append(rec)

                # Attribute queries (hostname, ips, timezone, domain) don't
                # emit JSONL -- dissect prints `<Target ...> <value>`. Detect
                # this case: no records parsed AND output is short text → wrap
                # the cleaned value as a single synthetic record so the table
                # shows it as "value: <the thing>".
                if not parsed_records and output.strip():
                    clean = output.strip()
                    import re as _re
                    clean = _re.sub(r"^<Target [^>]+>\s*", "", clean, count=1)
                    # Reject dissect diagnostics (plugin not applicable, stderr
                    # warnings). Wrapping these as synthetic records produces
                    # UI rows that look like evidence but are actually tool
                    # error text. Force the query into the failed/empty bucket.
                    if _re.search(r"\[(error|warning)\s*\]", clean):
                        raise ValueError(f"dissect diagnostic only, no data: {clean[:200]}")
                    # Only wrap as a single-value record if the output is
                    # clearly a short scalar (hostname/ips/timezone). Long
                    # output with no JSON is noise.
                    if len(clean) > 2000:
                        raise ValueError(f"long non-JSON output; not wrapping: {clean[:200]}")
                    parsed_records = [{"query": qfunc, "value": clean[:4000]}]
                    total_records = 1
                    parse_errors = 0

                # Aggregate prefetch into one-row-per-executable instead of
                # one-row-per-(exe, inner-file-ref). Raw dissect output is
                # hundreds of rows per .pf -- useless signal. We collapse to
                # {executable, run_count, last_runs, files_accessed_count,
                # sample_files} so the UI shows "1 row per program that ran".
                if qfunc == "prefetch":
                    by_exe: dict[str, dict[str, Any]] = {}
                    for rec in parsed_records:
                        exe = (rec.get("filename") or rec.get("previous_runs") or rec.get("name")
                               or rec.get("executable") or "<unknown>")
                        if isinstance(exe, dict):
                            exe = exe.get("executable", "<unknown>")
                        slot = by_exe.setdefault(str(exe), {
                            "executable": str(exe),
                            "run_count": rec.get("run_count"),
                            "last_run": rec.get("ts"),
                            "previous_runs": rec.get("previous_runs"),
                            "path": rec.get("linkedfile") or rec.get("path"),
                            "files_accessed_count": 0,
                            "sample_files": [],
                        })
                        slot["files_accessed_count"] += 1
                        ref = rec.get("linkedfile") or rec.get("filename_full") or rec.get("path")
                        if ref and len(slot["sample_files"]) < 15:
                            slot["sample_files"].append(str(ref))
                    for slot in by_exe.values():
                        _mark_suspicious(slot, candidate_fields=("executable", "path"), kind="prefetch")
                    # Put suspicious rows first so a human reviewer sees them immediately.
                    sorted_exe = sorted(
                        by_exe.values(),
                        key=lambda r: (0 if r.get("suspicious_reasons") else 1, -(r.get("run_count") or 0)),
                    )
                    records = sorted_exe[:max_records]
                    truncated = len(sorted_exe) > len(records)
                    total_records = len(sorted_exe)
                elif qfunc == "shellbags":
                    # Folder-browsing history. Aggregate 1 row per path with
                    # first/last seen + access count. Untouched raw output is
                    # one-row-per-registry-slot (thousands).
                    by_path: dict[str, dict[str, Any]] = {}
                    for rec in parsed_records:
                        p = (rec.get("path") or rec.get("full_path") or rec.get("file_path")
                             or rec.get("name") or "<unknown>")
                        slot = by_path.setdefault(str(p), {
                            "path": str(p),
                            "first_seen": rec.get("ts"),
                            "last_seen": rec.get("ts"),
                            "access_count": 0,
                        })
                        slot["access_count"] += 1
                        ts = rec.get("ts")
                        if ts:
                            if not slot["first_seen"] or ts < slot["first_seen"]:
                                slot["first_seen"] = ts
                            if not slot["last_seen"] or ts > slot["last_seen"]:
                                slot["last_seen"] = ts
                    for slot in by_path.values():
                        _mark_suspicious(slot, candidate_fields=("path",), kind="shellbags")
                    sorted_path = sorted(
                        by_path.values(),
                        key=lambda r: (0 if r.get("suspicious_reasons") else 1, r.get("last_seen") or ""),
                        reverse=False,
                    )
                    records = sorted_path[:max_records]
                    truncated = len(sorted_path) > len(records)
                    total_records = len(sorted_path)
                elif qfunc in ("runkeys", "services", "startupinfo", "tasks", "mru.recentdocs", "powershell_history", "recyclebin"):
                    # 1-row-per-entry queries -- already shaped well. Just enrich.
                    enriched: list[dict[str, Any]] = []
                    for rec in parsed_records:
                        _mark_suspicious(rec, candidate_fields=(
                            "command", "path", "executable", "image_path", "name", "servicedll",
                        ), kind=qfunc)
                        enriched.append(rec)
                    enriched.sort(key=lambda r: 0 if r.get("suspicious_reasons") else 1)
                    records = enriched[:max_records]
                    truncated = len(enriched) > len(records)
                    total_records = len(enriched)
                else:
                    records = parsed_records[:max_records]
                    truncated = len(parsed_records) > len(records)
                    # `total_records` above counted every stdout line including
                    # dissect's stderr warnings (merged via 2>&1). Re-ground
                    # it on successful parses so the "N record(s)" summary is
                    # honest and the truncated-banner doesn't fire at
                    # non-truncating counts like 33/33.
                    total_records = len(parsed_records)
                art = {
                    "family": family,
                    "type": qfunc.replace(".", "_"),
                    "source_tool": "dissect",
                    "data": {
                        "records": records,
                        "record_count": total_records,
                        "records_stored": len(records),
                        "truncated": truncated,
                        "parse_errors": parse_errors,
                        "raw_output": truncate(output, 4000),
                        "evidence_path": path,
                        "query_function": qfunc,
                    },
                }
                artifacts.append(art)
                if on_artifact:
                    await on_artifact(art)
                msg_suffix = (
                    f" -- {total_records} record(s), stored first {len(records)} (truncated)"
                    if truncated
                    else f" -- {len(records)} record(s)"
                )
                await safe_emit(
                    emitter, "artifact_added",
                    f"disk[{qfunc}]: ok in {elapsed:.1f}s{msg_suffix}",
                    {
                        "path": path, "query": qfunc, "type": family,
                        "elapsed_s": round(elapsed, 1),
                        "bytes": len(output),
                        "record_count": len(records),
                        "output_head": head_sample,
                        "output_tail": tail_sample,
                    },
                )
            else:
                await safe_emit(
                    emitter, "query_empty",
                    f"disk[{qfunc}]: empty result in {elapsed:.1f}s",
                    {"path": path, "query": qfunc, "elapsed_s": round(elapsed, 1)},
                )
        # ValueError covers our internal "diagnostic only, not data" signal
        # raised when dissect prints stderr warnings/errors instead of JSONL.
        # Without it here, that ValueError would escape the per-query loop
        # and crash the entire state into __crashed__.
        except (OSError, TimeoutError, RuntimeError, ValueError, AILAError) as exc:
            elapsed = _time.monotonic() - start_ts
            _log.debug("dissect query %s failed for %s: %s", qfunc, path, exc, exc_info=True)
            await safe_emit(
                emitter, "query_failed",
                f"disk[{qfunc}] failed after {elapsed:.1f}s: {exc}",
                {
                    "path": path, "query": qfunc,
                    "command": cmd,
                    "elapsed_s": round(elapsed, 1),
                    "error": str(exc)[:500],
                },
            )

    # Hotspot scan
    try:
        hotspot_exts = _HOTSPOT_EXTENSIONS_COMMON
        if image_os == "macos":
            hotspot_exts += f" -o -name {_HOTSPOT_EXTENSIONS_MACOS}"
        if analyzer_os == "windows":
            hotspot_cmd = (
                f'powershell -NoProfile -Command "Get-ChildItem -Recurse -File '
                f"-Path {sq(path, 'windows')} -Include *.exe,*.dll,*.ps1,*.bat,*.sh,*.py,*.elf,*.ko,*.dylib,*.app,*.pkg "
                f'| Select-Object FullName,Length,LastWriteTime | Format-Table -AutoSize"'
            )
        else:
            hotspot_cmd = (
                f"find {sq(path, 'linux')} -type f "
                rf"\( -name {hotspot_exts} \) "
                f"-printf '%T@ %s %p\\n' {esink} | sort -rn | head -50"
            )
        hotspot_output = await ssh.run_command(integration, hotspot_cmd, timeout_seconds=60.0)
        if hotspot_output.strip():
            art = {
                "family": "filesystem",
                "type": "suspicious_file_hotspots",
                "source_tool": "find",
                "data": {"raw_output": truncate(hotspot_output, 4000), "evidence_path": path},
            }
            artifacts.append(art)
            if on_artifact:
                await on_artifact(art)
            await safe_emit(emitter, "artifact_added", f"disk: hotspot scan ok for {path}", {"path": path, "type": "suspicious_file_hotspots"})
    except (OSError, TimeoutError, RuntimeError, AILAError) as exc:
        _log.debug("hotspot scan failed for %s: %s", path, exc, exc_info=True)
        await safe_emit(emitter, "query_failed", f"disk: hotspot scan failed: {exc}", {"path": path, "query": "hotspots", "error": str(exc)[:200]})

    return artifacts
